<?php
class Users extends CActiveRecord 
{
    
    /** Función para que el modelo se invoque por nombre */
    public static function model($model=__CLASS__) 
    {
        return parent::model($model);    
    }
    public function tableName()
    {
        return 'tbl_user'; // TODO: Change the autogenerated stub
    }
}